# Generated by Django 5.2.1 on 2025-05-09 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Vazirlik nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('established_date', models.DateField(verbose_name='Tashkil etilgan sana')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Rasmiy veb-sayt')),
            ],
            options={
                'verbose_name': 'Vazirlik',
                'verbose_name_plural': 'Vazirliklar',
            },
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Otasining ismi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ministers/', verbose_name='Rasm')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, verbose_name='Jinsi')),
                ('biography', models.TextField(verbose_name='Biografiya')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('appointment_date', models.DateField(verbose_name='Tayinlangan sana')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministers', to='goverment.ministry', verbose_name='Vazirlik')),
            ],
            options={
                'verbose_name': 'Vazir',
                'verbose_name_plural': 'Vazirlar',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Bo'lim nomi")),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('head', models.CharField(blank=True, max_length=200, null=True, verbose_name="Bo'lim boshlig'i")),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='goverment.ministry', verbose_name='Vazirlik')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Rasm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
    ]
