# Generated by Django 5.2.1 on 2025-05-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goverment', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minister',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
    ]
